#include "lilypond_exporter.h"
#include "../core/engine.h"
#include "../sequencer/pattern.h"
#include "../mixer/track.h"
#include "../instrument/instrument.h"
#include <fstream>
#include <sstream>
#include <map>

namespace disgrace_ns {

// Maps a MIDI note number to LilyPond's absolute pitch notation.
std::string LilyPondExporter::midi_to_lily(uint8_t note) {
    if (note >= 128) return "r"; // Return a rest for invalid notes
    
    static const char* names[] = {"c", "cis", "d", "dis", "e", "f", "fis", "g", "gis", "a", "ais", "b"};
    int pitch = note % 12;
    int octave = note / 12;
    
    // LilyPond absolute pitch: c' is middle C (C4, midi 60)
    std::string s = names[pitch];
    int lily_octave = octave - 4; // C4 is octave 4, which is the first ' octave in LilyPond

    if (lily_octave >= 0) {
        for (int i = 0; i <= lily_octave; ++i) s += "'";
    } else {
        for (int i = 0; i < -lily_octave; ++i) s += ",";
    }
    
    return s;
}

// Returns the clef string based on the track's notation type.
std::string LilyPondExporter::get_clef_string(int notation_type) {
    switch (static_cast<NotationType>(notation_type)) {
        case NotationType::Violin: return "treble";
        case NotationType::Bass: return "bass";
        case NotationType::ViolinBass: return "treble"; // The grand staff is handled specially.
        case NotationType::Drums: return "percussion";
        default: return "treble";
    }
}

// Generates the .ly source code for the entire project or a single track.
std::string LilyPondExporter::generate_ly_source(const Engine& engine, int track_index) {
    std::stringstream ss;
    ss << R"(\version "2.22.0")" << "\n\n";
    ss << R"(\header {)" << "\n";
    ss << R"(  title = "Disgrace Composition")" << "\n";
    ss << R"(  tagline = "Generated by Disgrace Tracker DAW")" << "\n";
    ss << R"(})" << "\n\n";

    auto order = engine.order_list();
    size_t num_tracks = engine.track_count();

    // Lambda to process a single track's data into LilyPond format.
    auto process_track = [&](size_t t) {
        const auto& track_obj = engine.track(t);
        ss << "track" << t << " = \\relative c' {\n"; // Use relative mode for easier note entry
        ss << "  \\clef " << get_clef_string((int)track_obj.notation()) << "\n";
        ss << "  \\time 4/4\n";
        
        for (auto pat_idx : order) {
            const auto& pat = engine.pattern(pat_idx);
            int pat_rows = (int)pat.row_count();
            
            for (int r = 0; r < pat_rows; ++r) {
                // Use the first note found in any column of the row
                bool note_found = false;
                for (size_t c = 0; c < pat.column_count(t); ++c) {
                    const auto& ev = pat.event(t, r, c);
                    if (ev.note < 128) {
                        ss << midi_to_lily(ev.note) << "16 ";
                        note_found = true;
                        break; 
                    }
                }
                if (!note_found) {
                    ss << "r16 "; // Rest if no note is found in the row
                }
                if ((r + 1) % 16 == 0) ss << "| % row " << r << "\n  ";
            }
        }
        ss << "\n}\n\n";
    };

    if (track_index == -1) { // Exporting the whole project
        for (size_t t = 0; t < num_tracks; ++t) {
            const auto& track_obj = engine.track(t);
            if (track_obj.instrument() && (track_obj.instrument()->type() == InstrumentType::SoundFont || track_obj.instrument()->type() == InstrumentType::Plugin || track_obj.instrument()->type() == InstrumentType::Midi)) {
                 process_track(t);
            }
        }

        ss << "\\score {\n  <<\n";
        for (size_t t = 0; t < num_tracks; ++t) {
            const auto& track_obj = engine.track(t);
             if (track_obj.instrument() && (track_obj.instrument()->type() == InstrumentType::SoundFont || track_obj.instrument()->type() == InstrumentType::Plugin || track_obj.instrument()->type() == InstrumentType::Midi)) {
                ss << "    \\new Staff \\with { instrumentName = #\"" << engine.track(t).name() << "\" } \\track" << t << "\n";
            }
        }
        ss << "  >>\n  \\layout { }\n  \\midi { }\n}\n";
    } else { // Exporting a single track
        process_track(track_index);
        ss << "\\score {\n  \\new Staff \\track" << track_index << "\n  \\layout { }\n}\n";
    }

    return ss.str();
}

// Writes the generated .ly source to a file.
bool LilyPondExporter::export_project(const Engine& engine, const std::string& path) {
    std::ofstream f(path);
    if (!f.is_open()) return false;
    f << generate_ly_source(engine);
    return f.good();
}

} // namespace disgrace_ns
